const content = {
  english: {
    homeLink: "Home",
    aboutLink: "About",
    projectsLink: "Projects",
    contactLink: "Contact",
    aboutTitle: "About",
    aboutParagraph: "English about me page",
    projectsTitle: "Projects",
    nameLabel: "Name",
    messageLabel: "Message",
    submitbtn: "Submit",
  },
  dutch: {
    homeLink: "Home",
    aboutLink: "Over Mij",
    projectsLink: "Projecten",
    contactLink: "Contact",
    aboutTitle: "Over Mij",
    aboutParagraph: "Dit is de about me paragraaf. ",
    projectsTitle: "Projecten",
    nameLabel: "Naam",
    messageLabel: "Bericht",
    submitbtn: "Verzend",
  },
};
